### ISSUE TITLE
When filtering by publication date, you cannot adjust the dates without reseting the whole search

### ISSUE THREAD

**Issue by kstapelfeldt** [digitalutsc/islandora_lite_solr_search#5]

**Comment by kstapelfeldt** [comment]
This will require modifying the URL-based query, so not a trivial piece of work. We look at the URL and see if there is a start and end date and then we have to replace the value.

**Comment by kstapelfeldt** [comment]
An interim step could be to change the theming so that it doesn't appear to a user that they can edit the refine fields.

**Comment by kylehuynh205** [comment]
**Scenario:** 
- Have isle-dc (islandora lite) running: 
- Have the site installation and ingesting is completed, the module (https://github.com/digitalutsc/facets_year_range) should be installed and enabled. 
- Go to `/search-results`, and enter the Publication Date on sidebar, enter a year range filter: 1998 to 2000, click Refine
- The page refresh with refresh button is replaced with "Reset" button instead, and From and To textboxes are disabled.
==> The reason for that: every time the Year range filter apply, it's added up as parameters in the URL, so we limit ONLY Year range filter in place. User has to reset the Year Range filter in order to do another Year range filter. 
Example: https://memory.digital.utsc.utoronto.ca/search-results?f%5B1%5D=publication_date%3A%28min%3A1999%2Cmax%3A2000%29

**TODO:** 
To improve the limit of each filter for year range once at a time, develop a handler to check current URL if it has year ranger filter params previously set, replace with the new one. so that user can do another filter without reset the whole current search.

**Comment by kylehuynh205** [comment]
- Tested and Merged Amy's PR 
- Also applied in our production sites:

https://doris3.digital.utsc.utoronto.ca/collection/1?f%5B0%5D=genre%3Aphotographs&f%5B1%5D=genre%3Atexts%20%28documents%29&f%5B2%5D=publication_date%3A(min%3A1998%2Cmax%3A2000)
